/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as PlanoRouteImport } from './routes/plano'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrcamentosIndexRouteImport } from './routes/orcamentos.index'
import { Route as EstoqueIndexRouteImport } from './routes/estoque.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SetupWhatsappRouteImport } from './routes/setup.whatsapp'
import { Route as ServicosNovoRouteImport } from './routes/servicos.novo'
import { Route as ServicosServicoIdRouteImport } from './routes/servicos.$servicoId'
import { Route as OrcamentosIdRouteImport } from './routes/orcamentos.$id'
import { Route as ClientesNovoRouteImport } from './routes/clientes.novo'
import { Route as ClientesClienteIdRouteImport } from './routes/clientes.$clienteId'
import { Route as CadastroEmpresaRouteImport } from './routes/cadastro.empresa'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminEmpresasIndexRouteImport } from './routes/admin.empresas.index'
import { Route as ApiWebhooksWooviRouteImport } from './routes/api/webhooks/woovi'
import { Route as ApiCronBillingRouteImport } from './routes/api/cron/billing'
import { Route as AdminEmpresasEmpresaIdRouteImport } from './routes/admin.empresas.$empresaId'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoRoute = PlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosIndexRoute = OrcamentosIndexRouteImport.update({
  id: '/orcamentos/',
  path: '/orcamentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueIndexRoute = EstoqueIndexRouteImport.update({
  id: '/estoque/',
  path: '/estoque/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SetupWhatsappRoute = SetupWhatsappRouteImport.update({
  id: '/setup/whatsapp',
  path: '/setup/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosNovoRoute = ServicosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosServicoIdRoute = ServicosServicoIdRouteImport.update({
  id: '/$servicoId',
  path: '/$servicoId',
  getParentRoute: () => ServicosRoute,
} as any)
const OrcamentosIdRoute = OrcamentosIdRouteImport.update({
  id: '/orcamentos/$id',
  path: '/orcamentos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesNovoRoute = ClientesNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => ClientesRoute,
} as any)
const ClientesClienteIdRoute = ClientesClienteIdRouteImport.update({
  id: '/$clienteId',
  path: '/$clienteId',
  getParentRoute: () => ClientesRoute,
} as any)
const CadastroEmpresaRoute = CadastroEmpresaRouteImport.update({
  id: '/cadastro/empresa',
  path: '/cadastro/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresasIndexRoute = AdminEmpresasIndexRouteImport.update({
  id: '/empresas/',
  path: '/empresas/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiWebhooksWooviRoute = ApiWebhooksWooviRouteImport.update({
  id: '/api/webhooks/woovi',
  path: '/api/webhooks/woovi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronBillingRoute = ApiCronBillingRouteImport.update({
  id: '/api/cron/billing',
  path: '/api/cron/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmpresasEmpresaIdRoute = AdminEmpresasEmpresaIdRouteImport.update({
  id: '/empresas/$empresaId',
  path: '/empresas/$empresaId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/clientes': typeof ClientesRouteWithChildren
  '/empresa': typeof EmpresaRoute
  '/financeiro': typeof FinanceiroRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/plano': typeof PlanoRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/cadastro/empresa': typeof CadastroEmpresaRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/orcamentos/$id': typeof OrcamentosIdRoute
  '/servicos/$servicoId': typeof ServicosServicoIdRoute
  '/servicos/novo': typeof ServicosNovoRoute
  '/setup/whatsapp': typeof SetupWhatsappRoute
  '/admin/': typeof AdminIndexRoute
  '/estoque/': typeof EstoqueIndexRoute
  '/orcamentos/': typeof OrcamentosIndexRoute
  '/admin/empresas/$empresaId': typeof AdminEmpresasEmpresaIdRoute
  '/api/cron/billing': typeof ApiCronBillingRoute
  '/api/webhooks/woovi': typeof ApiWebhooksWooviRoute
  '/admin/empresas/': typeof AdminEmpresasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/empresa': typeof EmpresaRoute
  '/financeiro': typeof FinanceiroRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/plano': typeof PlanoRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/cadastro/empresa': typeof CadastroEmpresaRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/orcamentos/$id': typeof OrcamentosIdRoute
  '/servicos/$servicoId': typeof ServicosServicoIdRoute
  '/servicos/novo': typeof ServicosNovoRoute
  '/setup/whatsapp': typeof SetupWhatsappRoute
  '/admin': typeof AdminIndexRoute
  '/estoque': typeof EstoqueIndexRoute
  '/orcamentos': typeof OrcamentosIndexRoute
  '/admin/empresas/$empresaId': typeof AdminEmpresasEmpresaIdRoute
  '/api/cron/billing': typeof ApiCronBillingRoute
  '/api/webhooks/woovi': typeof ApiWebhooksWooviRoute
  '/admin/empresas': typeof AdminEmpresasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/clientes': typeof ClientesRouteWithChildren
  '/empresa': typeof EmpresaRoute
  '/financeiro': typeof FinanceiroRoute
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/plano': typeof PlanoRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/cadastro/empresa': typeof CadastroEmpresaRoute
  '/clientes/$clienteId': typeof ClientesClienteIdRoute
  '/clientes/novo': typeof ClientesNovoRoute
  '/orcamentos/$id': typeof OrcamentosIdRoute
  '/servicos/$servicoId': typeof ServicosServicoIdRoute
  '/servicos/novo': typeof ServicosNovoRoute
  '/setup/whatsapp': typeof SetupWhatsappRoute
  '/admin/': typeof AdminIndexRoute
  '/estoque/': typeof EstoqueIndexRoute
  '/orcamentos/': typeof OrcamentosIndexRoute
  '/admin/empresas/$empresaId': typeof AdminEmpresasEmpresaIdRoute
  '/api/cron/billing': typeof ApiCronBillingRoute
  '/api/webhooks/woovi': typeof ApiWebhooksWooviRoute
  '/admin/empresas/': typeof AdminEmpresasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/clientes'
    | '/empresa'
    | '/financeiro'
    | '/kanban'
    | '/login'
    | '/menu'
    | '/plano'
    | '/servicos'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/login'
    | '/cadastro/empresa'
    | '/clientes/$clienteId'
    | '/clientes/novo'
    | '/orcamentos/$id'
    | '/servicos/$servicoId'
    | '/servicos/novo'
    | '/setup/whatsapp'
    | '/admin/'
    | '/estoque/'
    | '/orcamentos/'
    | '/admin/empresas/$empresaId'
    | '/api/cron/billing'
    | '/api/webhooks/woovi'
    | '/admin/empresas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/empresa'
    | '/financeiro'
    | '/kanban'
    | '/login'
    | '/menu'
    | '/plano'
    | '/servicos'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/login'
    | '/cadastro/empresa'
    | '/clientes/$clienteId'
    | '/clientes/novo'
    | '/orcamentos/$id'
    | '/servicos/$servicoId'
    | '/servicos/novo'
    | '/setup/whatsapp'
    | '/admin'
    | '/estoque'
    | '/orcamentos'
    | '/admin/empresas/$empresaId'
    | '/api/cron/billing'
    | '/api/webhooks/woovi'
    | '/admin/empresas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/clientes'
    | '/empresa'
    | '/financeiro'
    | '/kanban'
    | '/login'
    | '/menu'
    | '/plano'
    | '/servicos'
    | '/admin/configuracoes'
    | '/admin/dashboard'
    | '/admin/login'
    | '/cadastro/empresa'
    | '/clientes/$clienteId'
    | '/clientes/novo'
    | '/orcamentos/$id'
    | '/servicos/$servicoId'
    | '/servicos/novo'
    | '/setup/whatsapp'
    | '/admin/'
    | '/estoque/'
    | '/orcamentos/'
    | '/admin/empresas/$empresaId'
    | '/api/cron/billing'
    | '/api/webhooks/woovi'
    | '/admin/empresas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientesRoute: typeof ClientesRouteWithChildren
  EmpresaRoute: typeof EmpresaRoute
  FinanceiroRoute: typeof FinanceiroRoute
  KanbanRoute: typeof KanbanRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  PlanoRoute: typeof PlanoRoute
  ServicosRoute: typeof ServicosRouteWithChildren
  CadastroEmpresaRoute: typeof CadastroEmpresaRoute
  OrcamentosIdRoute: typeof OrcamentosIdRoute
  SetupWhatsappRoute: typeof SetupWhatsappRoute
  EstoqueIndexRoute: typeof EstoqueIndexRoute
  OrcamentosIndexRoute: typeof OrcamentosIndexRoute
  ApiCronBillingRoute: typeof ApiCronBillingRoute
  ApiWebhooksWooviRoute: typeof ApiWebhooksWooviRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano': {
      id: '/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof PlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos/': {
      id: '/orcamentos/'
      path: '/orcamentos'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof OrcamentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque/': {
      id: '/estoque/'
      path: '/estoque'
      fullPath: '/estoque/'
      preLoaderRoute: typeof EstoqueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/setup/whatsapp': {
      id: '/setup/whatsapp'
      path: '/setup/whatsapp'
      fullPath: '/setup/whatsapp'
      preLoaderRoute: typeof SetupWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/novo': {
      id: '/servicos/novo'
      path: '/novo'
      fullPath: '/servicos/novo'
      preLoaderRoute: typeof ServicosNovoRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/$servicoId': {
      id: '/servicos/$servicoId'
      path: '/$servicoId'
      fullPath: '/servicos/$servicoId'
      preLoaderRoute: typeof ServicosServicoIdRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/orcamentos/$id': {
      id: '/orcamentos/$id'
      path: '/orcamentos/$id'
      fullPath: '/orcamentos/$id'
      preLoaderRoute: typeof OrcamentosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/novo': {
      id: '/clientes/novo'
      path: '/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof ClientesNovoRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/clientes/$clienteId': {
      id: '/clientes/$clienteId'
      path: '/$clienteId'
      fullPath: '/clientes/$clienteId'
      preLoaderRoute: typeof ClientesClienteIdRouteImport
      parentRoute: typeof ClientesRoute
    }
    '/cadastro/empresa': {
      id: '/cadastro/empresa'
      path: '/cadastro/empresa'
      fullPath: '/cadastro/empresa'
      preLoaderRoute: typeof CadastroEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empresas/': {
      id: '/admin/empresas/'
      path: '/empresas'
      fullPath: '/admin/empresas/'
      preLoaderRoute: typeof AdminEmpresasIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/webhooks/woovi': {
      id: '/api/webhooks/woovi'
      path: '/api/webhooks/woovi'
      fullPath: '/api/webhooks/woovi'
      preLoaderRoute: typeof ApiWebhooksWooviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/billing': {
      id: '/api/cron/billing'
      path: '/api/cron/billing'
      fullPath: '/api/cron/billing'
      preLoaderRoute: typeof ApiCronBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/empresas/$empresaId': {
      id: '/admin/empresas/$empresaId'
      path: '/empresas/$empresaId'
      fullPath: '/admin/empresas/$empresaId'
      preLoaderRoute: typeof AdminEmpresasEmpresaIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEmpresasEmpresaIdRoute: typeof AdminEmpresasEmpresaIdRoute
  AdminEmpresasIndexRoute: typeof AdminEmpresasIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEmpresasEmpresaIdRoute: AdminEmpresasEmpresaIdRoute,
  AdminEmpresasIndexRoute: AdminEmpresasIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientesRouteChildren {
  ClientesClienteIdRoute: typeof ClientesClienteIdRoute
  ClientesNovoRoute: typeof ClientesNovoRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesClienteIdRoute: ClientesClienteIdRoute,
  ClientesNovoRoute: ClientesNovoRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

interface ServicosRouteChildren {
  ServicosServicoIdRoute: typeof ServicosServicoIdRoute
  ServicosNovoRoute: typeof ServicosNovoRoute
}

const ServicosRouteChildren: ServicosRouteChildren = {
  ServicosServicoIdRoute: ServicosServicoIdRoute,
  ServicosNovoRoute: ServicosNovoRoute,
}

const ServicosRouteWithChildren = ServicosRoute._addFileChildren(
  ServicosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientesRoute: ClientesRouteWithChildren,
  EmpresaRoute: EmpresaRoute,
  FinanceiroRoute: FinanceiroRoute,
  KanbanRoute: KanbanRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  PlanoRoute: PlanoRoute,
  ServicosRoute: ServicosRouteWithChildren,
  CadastroEmpresaRoute: CadastroEmpresaRoute,
  OrcamentosIdRoute: OrcamentosIdRoute,
  SetupWhatsappRoute: SetupWhatsappRoute,
  EstoqueIndexRoute: EstoqueIndexRoute,
  OrcamentosIndexRoute: OrcamentosIndexRoute,
  ApiCronBillingRoute: ApiCronBillingRoute,
  ApiWebhooksWooviRoute: ApiWebhooksWooviRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
